DROP TABLE IF EXISTS daArtifact;
CREATE TABLE IF NOT EXISTS daArtifact (
  id INT NOT NULL AUTO_INCREMENT,
  docName VARCHAR (64) NOT NULL DEFAULT "",
  digest VARCHAR (64) NOT NULL DEFAULT "",
  size INT NOT NULL DEFAULT 0,
  fileName VARCHAR (256) NOT NULL DEFAULT "",
  fileExtension CHAR (16) NOT NULL DEFAULT "",
  mimeType VARCHAR (64) NOT NULL DEFAULT "application/octet-stream",
  notes TEXT NOT NULL DEFAULT "",
  PRIMARY KEY (id)
) DEFAULT CHARSET='utf8' COLLATE='utf8_general_ci' AUTO_INCREMENT=1;

DROP TABLE IF EXISTS daTag;
CREATE TABLE IF NOT EXISTS daTag (
  id INT NOT NULL AUTO_INCREMENT,
  tagName VARCHAR(128) NOT NULL,
  PRIMARY KEY (id)
) DEFAULT CHARSET='utf8' COLLATE='utf8_general_ci' AUTO_INCREMENT=1;

DROP TABLE IF EXISTS daArtifactTags;
CREATE TABLE IF NOT EXISTS daArtifactTags (
  artifactId INT NOT NULL,
  tagId INT NOT NULL,
  PRIMARY KEY (artifactId,tagId)
) DEFAULT CHARSET='utf8' COLLATE='utf8_general_ci';
